request-log-pipeline:
  source:
    otel_logs_source:
      ssl: false
      port: 21894
  sink:
    - opensearch:
        hosts: ["http://opensearch-node:9200"]
        insecure: true
        index: request_logs
log-pipeline:
  source:
    otel_logs_source:
      ssl: false
      port: 21892
  sink:
    - opensearch:
        hosts: ["http://opensearch-node:9200"]
        insecure: true
        index: app_log
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch-node:9200" ]
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["http://opensearch-node:9200"]
        index_type: trace-analytics-service-map

